export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
export const USER_BLOCKING_STATE_CHANGE = 'USER_BLOCKING_STATE_CHANGE'
export const LIKES_STATE_CHANGE = 'LIKES_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const NFL_GAMES_STATE_CHANGE = 'NFL_GAMES_STATE_CHANGE'
export const NCAAF_GAMES_STATE_CHANGE = 'NCAAF_GAMES_STATE_CHANGE'
export const MLB_GAMES_STATE_CHANGE = 'MLB_GAMES_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'



