export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
export const USER_BLOCKING_STATE_CHANGE = 'USER_BLOCKING_STATE_CHANGE'
export const LIKES_STATE_CHANGE = 'LIKES_STATE_CHANGE'
export const FADES_STATE_CHANGE = 'FADES_STATE_CHANGE'

export const ALL_USERS_STATE_CHANGE = 'ALL_USERS_STATE_CHANGE'

export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const NFL_GAMES_STATE_CHANGE = 'NFL_GAMES_STATE_CHANGE'
export const NCAAF_GAMES_STATE_CHANGE = 'NCAAF_GAMES_STATE_CHANGE'
export const MLB_GAMES_STATE_CHANGE = 'MLB_GAMES_STATE_CHANGE'
export const NBA_GAMES_STATE_CHANGE = 'NBA_GAMES_STATE_CHANGE'
export const NCAAB_GAMES_STATE_CHANGE = 'NCAAB_GAMES_STATE_CHANGE'
export const NHL_GAMES_STATE_CHANGE = 'NHL_GAMES_STATE_CHANGE'
export const EPL_GAMES_STATE_CHANGE = 'EPL_GAMES_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'



